
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programCOMMA DOT EXAMPLE_KEY IMPLIES LPAREN MARKER MAX MIN MODEB_KEY MODEH_KEY NOT OPERATOR PREDICATE PRIORITY RPAREN TERM WEIGHTprogram : program clause\n               | clauseclause : example\n              | modeb\n              | modeh\n              | fact\n              | normal_clause\n              | constraint\n    atom : PREDICATE LPAREN terms RPAREN\n    schema : PREDICATE LPAREN schema_terms RPARENschema_terms : MARKER TERM\n                    | MARKER TERM COMMA schema_terms\n                    | schema\n                    | schema COMMA schema_terms\n    min_max_bias : MAX TERM MIN TERM\n                    | MAX TERM\n    priority_bias : PRIORITY TERMweight_bias : WEIGHT TERMbias : min_max_bias weight_bias priority_bias\n            | min_max_bias priority_bias\n            | min_max_bias weight_bias\n            | weight_bias priority_bias\n            | weight_bias\n            | priority_bias\n            | min_max_bias\n    example : EXAMPLE_KEY atom DOT\n               | EXAMPLE_KEY NOT atom DOT\n               | EXAMPLE_KEY atom bias DOT\n               | EXAMPLE_KEY NOT atom bias DOT\n    modeh : MODEH_KEY schema DOT\n             | MODEH_KEY schema bias DOT\n    modeb : MODEB_KEY schema DOT\n             | MODEB_KEY NOT schema DOT\n             | MODEB_KEY schema bias DOT\n             | MODEB_KEY NOT schema bias DOT\n             terms : TERM\n             | atom\n             | TERM COMMA terms\n             | atom COMMA terms\n    fact : atom DOT\n    constraint : NOT body DOT\n    normal_clause : atom IMPLIES body DOT\n    body : literal COMMA body\n            | literal\n    literal : NOT atom\n               | atom\n               | TERM OPERATOR TERM\n    '
    
_lr_action_items = {'EXAMPLE_KEY':([0,1,2,3,4,5,6,7,8,15,18,30,41,44,48,53,60,62,65,66,71,77,78,],[9,9,-2,-3,-4,-5,-6,-7,-8,-1,-40,-26,-41,-32,-30,-28,-27,-42,-34,-33,-31,-29,-35,]),'MODEB_KEY':([0,1,2,3,4,5,6,7,8,15,18,30,41,44,48,53,60,62,65,66,71,77,78,],[12,12,-2,-3,-4,-5,-6,-7,-8,-1,-40,-26,-41,-32,-30,-28,-27,-42,-34,-33,-31,-29,-35,]),'MODEH_KEY':([0,1,2,3,4,5,6,7,8,15,18,30,41,44,48,53,60,62,65,66,71,77,78,],[13,13,-2,-3,-4,-5,-6,-7,-8,-1,-40,-26,-41,-32,-30,-28,-27,-42,-34,-33,-31,-29,-35,]),'NOT':([0,1,2,3,4,5,6,7,8,9,11,12,15,18,19,30,41,42,44,48,53,60,62,65,66,71,77,78,],[11,11,-2,-3,-4,-5,-6,-7,-8,17,20,26,-1,-40,20,-26,-41,20,-32,-30,-28,-27,-42,-34,-33,-31,-29,-35,]),'PREDICATE':([0,1,2,3,4,5,6,7,8,9,11,12,13,15,17,18,19,20,26,29,30,41,42,44,47,48,53,60,62,65,66,71,73,74,77,78,81,85,],[14,14,-2,-3,-4,-5,-6,-7,-8,14,14,27,27,-1,14,-40,14,14,27,14,-26,-41,14,-32,27,-30,-28,-27,-42,-34,-33,-31,14,14,-29,-35,27,27,]),'$end':([1,2,3,4,5,6,7,8,15,18,30,41,44,48,53,60,62,65,66,71,77,78,],[0,-2,-3,-4,-5,-6,-7,-8,-1,-40,-26,-41,-32,-30,-28,-27,-42,-34,-33,-31,-29,-35,]),'DOT':([10,16,21,22,23,25,28,31,32,33,34,38,39,40,45,46,49,54,55,56,57,58,59,61,63,64,67,72,75,79,84,],[18,30,41,-44,-46,44,48,53,-25,-23,-24,60,62,-45,65,66,71,-21,-20,-22,-16,-18,-17,77,-43,-47,78,-9,-19,-10,-15,]),'IMPLIES':([10,72,],[19,-9,]),'TERM':([11,19,29,35,36,37,42,43,69,73,74,76,],[24,24,51,57,58,59,24,64,80,51,51,84,]),'LPAREN':([14,27,],[29,47,]),'MAX':([16,25,28,38,46,72,79,],[35,35,35,35,35,-9,-10,]),'WEIGHT':([16,25,28,32,38,46,57,72,79,84,],[36,36,36,36,36,36,-16,-9,-10,-15,]),'PRIORITY':([16,25,28,32,33,38,46,54,57,58,72,79,84,],[37,37,37,37,37,37,37,37,-16,-18,-9,-10,-15,]),'COMMA':([22,23,40,51,52,64,70,72,79,80,],[42,-46,-45,73,74,-47,81,-9,-10,85,]),'OPERATOR':([24,],[43,]),'MARKER':([47,81,85,],[69,69,69,]),'RPAREN':([50,51,52,68,70,72,79,80,82,83,86,87,],[72,-36,-37,79,-13,-9,-10,-11,-38,-39,-14,-12,]),'MIN':([57,],[76,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'clause':([0,1,],[2,15,]),'example':([0,1,],[3,3,]),'modeb':([0,1,],[4,4,]),'modeh':([0,1,],[5,5,]),'fact':([0,1,],[6,6,]),'normal_clause':([0,1,],[7,7,]),'constraint':([0,1,],[8,8,]),'atom':([0,1,9,11,17,19,20,29,42,73,74,],[10,10,16,23,38,23,40,52,23,52,52,]),'body':([11,19,42,],[21,39,63,]),'literal':([11,19,42,],[22,22,22,]),'schema':([12,13,26,47,81,85,],[25,28,46,70,70,70,]),'bias':([16,25,28,38,46,],[31,45,49,61,67,]),'min_max_bias':([16,25,28,38,46,],[32,32,32,32,32,]),'weight_bias':([16,25,28,32,38,46,],[33,33,33,54,33,33,]),'priority_bias':([16,25,28,32,33,38,46,54,],[34,34,34,55,56,34,34,75,]),'terms':([29,73,74,],[50,82,83,]),'schema_terms':([47,81,85,],[68,86,87,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program clause','program',2,'p_program','parser.py',60),
  ('program -> clause','program',1,'p_program','parser.py',61),
  ('clause -> example','clause',1,'p_clause','parser.py',68),
  ('clause -> modeb','clause',1,'p_clause','parser.py',69),
  ('clause -> modeh','clause',1,'p_clause','parser.py',70),
  ('clause -> fact','clause',1,'p_clause','parser.py',71),
  ('clause -> normal_clause','clause',1,'p_clause','parser.py',72),
  ('clause -> constraint','clause',1,'p_clause','parser.py',73),
  ('atom -> PREDICATE LPAREN terms RPAREN','atom',4,'p_atom','parser.py',80),
  ('schema -> PREDICATE LPAREN schema_terms RPAREN','schema',4,'p_schema','parser.py',86),
  ('schema_terms -> MARKER TERM','schema_terms',2,'p_schema_terms','parser.py',90),
  ('schema_terms -> MARKER TERM COMMA schema_terms','schema_terms',4,'p_schema_terms','parser.py',91),
  ('schema_terms -> schema','schema_terms',1,'p_schema_terms','parser.py',92),
  ('schema_terms -> schema COMMA schema_terms','schema_terms',3,'p_schema_terms','parser.py',93),
  ('min_max_bias -> MAX TERM MIN TERM','min_max_bias',4,'p_min_max_bias','parser.py',105),
  ('min_max_bias -> MAX TERM','min_max_bias',2,'p_min_max_bias','parser.py',106),
  ('priority_bias -> PRIORITY TERM','priority_bias',2,'p_priority_bias','parser.py',117),
  ('weight_bias -> WEIGHT TERM','weight_bias',2,'p_weight_bias','parser.py',121),
  ('bias -> min_max_bias weight_bias priority_bias','bias',3,'p_bias','parser.py',125),
  ('bias -> min_max_bias priority_bias','bias',2,'p_bias','parser.py',126),
  ('bias -> min_max_bias weight_bias','bias',2,'p_bias','parser.py',127),
  ('bias -> weight_bias priority_bias','bias',2,'p_bias','parser.py',128),
  ('bias -> weight_bias','bias',1,'p_bias','parser.py',129),
  ('bias -> priority_bias','bias',1,'p_bias','parser.py',130),
  ('bias -> min_max_bias','bias',1,'p_bias','parser.py',131),
  ('example -> EXAMPLE_KEY atom DOT','example',3,'p_example','parser.py',148),
  ('example -> EXAMPLE_KEY NOT atom DOT','example',4,'p_example','parser.py',149),
  ('example -> EXAMPLE_KEY atom bias DOT','example',4,'p_example','parser.py',150),
  ('example -> EXAMPLE_KEY NOT atom bias DOT','example',5,'p_example','parser.py',151),
  ('modeh -> MODEH_KEY schema DOT','modeh',3,'p_modeh','parser.py',177),
  ('modeh -> MODEH_KEY schema bias DOT','modeh',4,'p_modeh','parser.py',178),
  ('modeb -> MODEB_KEY schema DOT','modeb',3,'p_modeb','parser.py',196),
  ('modeb -> MODEB_KEY NOT schema DOT','modeb',4,'p_modeb','parser.py',197),
  ('modeb -> MODEB_KEY schema bias DOT','modeb',4,'p_modeb','parser.py',198),
  ('modeb -> MODEB_KEY NOT schema bias DOT','modeb',5,'p_modeb','parser.py',199),
  ('terms -> TERM','terms',1,'p_terms','parser.py',227),
  ('terms -> atom','terms',1,'p_terms','parser.py',228),
  ('terms -> TERM COMMA terms','terms',3,'p_terms','parser.py',229),
  ('terms -> atom COMMA terms','terms',3,'p_terms','parser.py',230),
  ('fact -> atom DOT','fact',2,'p_fact','parser.py',243),
  ('constraint -> NOT body DOT','constraint',3,'p_constraint','parser.py',249),
  ('normal_clause -> atom IMPLIES body DOT','normal_clause',4,'p_normal_clause','parser.py',255),
  ('body -> literal COMMA body','body',3,'p_body','parser.py',260),
  ('body -> literal','body',1,'p_body','parser.py',261),
  ('literal -> NOT atom','literal',2,'p_literal','parser.py',269),
  ('literal -> atom','literal',1,'p_literal','parser.py',270),
  ('literal -> TERM OPERATOR TERM','literal',3,'p_literal','parser.py',271),
]
