
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'programCOMMA DOT EXAMPLE_KEY IMPLIES LPAREN MARKER MODEB_KEY MODEH_KEY NOT PREDICATE RPAREN TERMprogram : program clause\n               | clauseclause : example\n              | modeb\n              | modeh\n              | fact\n              | normal_clause\n              | constraint\n    atom : PREDICATE LPAREN terms RPARENschema : PREDICATE LPAREN schema_terms RPARENschema_terms : MARKER TERM\n                    | MARKER TERM COMMA schema_terms\n                    | schema\n                    | schema COMMA schema_terms\n    example : EXAMPLE_KEY atom DOT\n               | EXAMPLE_KEY NOT atom DOT\n    modeh : MODEH_KEY schema DOTmodeb : MODEB_KEY schema DOT\n             | MODEB_KEY NOT schema DOT\n             terms : TERM\n             | atom\n             | TERM COMMA terms\n             | atom COMMA terms\n    fact : atom DOT\n    constraint : NOT body DOT\n    normal_clause : atom IMPLIES body DOT\n    body : literal COMMA body\n            | literal\n    literal : NOT atom\n               | atom\n    '
    
_lr_action_items = {'EXAMPLE_KEY':([0,1,2,3,4,5,6,7,8,15,18,29,33,35,38,42,43,45,],[9,9,-2,-3,-4,-5,-6,-7,-8,-1,-24,-15,-25,-18,-17,-16,-26,-19,]),'MODEB_KEY':([0,1,2,3,4,5,6,7,8,15,18,29,33,35,38,42,43,45,],[12,12,-2,-3,-4,-5,-6,-7,-8,-1,-24,-15,-25,-18,-17,-16,-26,-19,]),'MODEH_KEY':([0,1,2,3,4,5,6,7,8,15,18,29,33,35,38,42,43,45,],[13,13,-2,-3,-4,-5,-6,-7,-8,-1,-24,-15,-25,-18,-17,-16,-26,-19,]),'NOT':([0,1,2,3,4,5,6,7,8,9,11,12,15,18,19,29,33,34,35,38,42,43,45,],[11,11,-2,-3,-4,-5,-6,-7,-8,17,20,25,-1,-24,20,-15,-25,20,-18,-17,-16,-26,-19,]),'PREDICATE':([0,1,2,3,4,5,6,7,8,9,11,12,13,15,17,18,19,20,25,28,29,33,34,35,37,38,42,43,45,50,51,54,57,],[14,14,-2,-3,-4,-5,-6,-7,-8,14,14,26,26,-1,14,-24,14,14,26,14,-15,-25,14,-18,26,-17,-16,-26,-19,14,14,26,26,]),'$end':([1,2,3,4,5,6,7,8,15,18,29,33,35,38,42,43,45,],[0,-2,-3,-4,-5,-6,-7,-8,-1,-24,-15,-25,-18,-17,-16,-26,-19,]),'DOT':([10,16,21,22,23,24,27,30,31,32,36,44,49,52,],[18,29,33,-28,-30,35,38,42,43,-29,45,-27,-9,-10,]),'IMPLIES':([10,49,],[19,-9,]),'LPAREN':([14,26,],[28,37,]),'COMMA':([22,23,32,40,41,48,49,52,53,],[34,-30,-29,50,51,54,-9,-10,57,]),'TERM':([28,47,50,51,],[40,53,40,40,]),'MARKER':([37,54,57,],[47,47,47,]),'RPAREN':([39,40,41,46,48,49,52,53,55,56,58,59,],[49,-20,-21,52,-13,-9,-10,-11,-22,-23,-14,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'clause':([0,1,],[2,15,]),'example':([0,1,],[3,3,]),'modeb':([0,1,],[4,4,]),'modeh':([0,1,],[5,5,]),'fact':([0,1,],[6,6,]),'normal_clause':([0,1,],[7,7,]),'constraint':([0,1,],[8,8,]),'atom':([0,1,9,11,17,19,20,28,34,50,51,],[10,10,16,23,30,23,32,41,23,41,41,]),'body':([11,19,34,],[21,31,44,]),'literal':([11,19,34,],[22,22,22,]),'schema':([12,13,25,37,54,57,],[24,27,36,48,48,48,]),'terms':([28,50,51,],[39,55,56,]),'schema_terms':([37,54,57,],[46,58,59,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> program clause','program',2,'p_program','parser.py',49),
  ('program -> clause','program',1,'p_program','parser.py',50),
  ('clause -> example','clause',1,'p_clause','parser.py',57),
  ('clause -> modeb','clause',1,'p_clause','parser.py',58),
  ('clause -> modeh','clause',1,'p_clause','parser.py',59),
  ('clause -> fact','clause',1,'p_clause','parser.py',60),
  ('clause -> normal_clause','clause',1,'p_clause','parser.py',61),
  ('clause -> constraint','clause',1,'p_clause','parser.py',62),
  ('atom -> PREDICATE LPAREN terms RPAREN','atom',4,'p_atom','parser.py',69),
  ('schema -> PREDICATE LPAREN schema_terms RPAREN','schema',4,'p_schema','parser.py',74),
  ('schema_terms -> MARKER TERM','schema_terms',2,'p_schema_terms','parser.py',78),
  ('schema_terms -> MARKER TERM COMMA schema_terms','schema_terms',4,'p_schema_terms','parser.py',79),
  ('schema_terms -> schema','schema_terms',1,'p_schema_terms','parser.py',80),
  ('schema_terms -> schema COMMA schema_terms','schema_terms',3,'p_schema_terms','parser.py',81),
  ('example -> EXAMPLE_KEY atom DOT','example',3,'p_example','parser.py',94),
  ('example -> EXAMPLE_KEY NOT atom DOT','example',4,'p_example','parser.py',95),
  ('modeh -> MODEH_KEY schema DOT','modeh',3,'p_modeh','parser.py',104),
  ('modeb -> MODEB_KEY schema DOT','modeb',3,'p_modeb','parser.py',109),
  ('modeb -> MODEB_KEY NOT schema DOT','modeb',4,'p_modeb','parser.py',110),
  ('terms -> TERM','terms',1,'p_terms','parser.py',119),
  ('terms -> atom','terms',1,'p_terms','parser.py',120),
  ('terms -> TERM COMMA terms','terms',3,'p_terms','parser.py',121),
  ('terms -> atom COMMA terms','terms',3,'p_terms','parser.py',122),
  ('fact -> atom DOT','fact',2,'p_fact','parser.py',135),
  ('constraint -> NOT body DOT','constraint',3,'p_constraint','parser.py',141),
  ('normal_clause -> atom IMPLIES body DOT','normal_clause',4,'p_normal_clause','parser.py',147),
  ('body -> literal COMMA body','body',3,'p_body','parser.py',152),
  ('body -> literal','body',1,'p_body','parser.py',153),
  ('literal -> NOT atom','literal',2,'p_literal','parser.py',161),
  ('literal -> atom','literal',1,'p_literal','parser.py',162),
]
